/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_administrateur (void)
{
  GtkWidget *window_administrateur;
  GtkWidget *fixed2;
  GtkWidget *ajouter;
  GtkWidget *modifier;
  GtkWidget *supprimer;
  GtkWidget *rechercher;
  GtkWidget *button_retour_espace_admin;
  GtkWidget *alignment14;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label41;

  window_administrateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_administrateur), _("administrateur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window_administrateur), fixed2);

  ajouter = gtk_button_new_with_mnemonic (_("ajouter un equipement"));
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter, 32, 32);
  gtk_widget_set_size_request (ajouter, 352, 72);

  modifier = gtk_button_new_with_mnemonic (_("modifier un equipement"));
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), modifier, 32, 112);
  gtk_widget_set_size_request (modifier, 352, 80);

  supprimer = gtk_button_new_with_mnemonic (_("supprimer un equipement"));
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), supprimer, 32, 200);
  gtk_widget_set_size_request (supprimer, 352, 88);

  rechercher = gtk_button_new_with_mnemonic (_("rechercher un equipement"));
  gtk_widget_show (rechercher);
  gtk_fixed_put (GTK_FIXED (fixed2), rechercher, 32, 296);
  gtk_widget_set_size_request (rechercher, 352, 88);

  button_retour_espace_admin = gtk_button_new ();
  gtk_widget_show (button_retour_espace_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), button_retour_espace_admin, 144, 400);
  gtk_widget_set_size_request (button_retour_espace_admin, 112, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_retour_espace_admin), alignment14);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox11), label41, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercher, "clicked",
                    G_CALLBACK (on_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_espace_admin, "clicked",
                    G_CALLBACK (on_button_retour_espace_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_administrateur, window_administrateur, "window_administrateur");
  GLADE_HOOKUP_OBJECT (window_administrateur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_administrateur, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (window_administrateur, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (window_administrateur, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (window_administrateur, rechercher, "rechercher");
  GLADE_HOOKUP_OBJECT (window_administrateur, button_retour_espace_admin, "button_retour_espace_admin");
  GLADE_HOOKUP_OBJECT (window_administrateur, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window_administrateur, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window_administrateur, image11, "image11");
  GLADE_HOOKUP_OBJECT (window_administrateur, label41, "label41");

  return window_administrateur;
}

GtkWidget*
create_window_rechercher (void)
{
  GtkWidget *window_rechercher;
  GtkWidget *alignment1;
  GtkWidget *eventbox1;
  GtkWidget *fixed4;
  GtkWidget *entry_recherche_imen;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview_equipement_imen;
  GtkWidget *label56;
  GtkWidget *label74;
  GtkWidget *label51;
  GtkWidget *image13;
  GtkWidget *label32;
  GtkWidget *button_rechercher;
  GtkWidget *alignment16;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label52;
  GtkWidget *recherche_modifier;
  GtkWidget *alignment20;
  GtkWidget *hbox17;
  GtkWidget *image21;
  GtkWidget *label73;
  GtkWidget *button_annuler;
  GtkWidget *alignment23;
  GtkWidget *hbox20;
  GtkWidget *image24;
  GtkWidget *label81;
  GtkWidget *checkbutton_disponible;
  GtkWidget *checkbutton_reserver_equi;
  GtkWidget *checkbutton_maintenance;

  window_rechercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_rechercher), _("rechercher"));
  gtk_window_set_default_size (GTK_WINDOW (window_rechercher), 4, 100);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (window_rechercher), alignment1);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), eventbox1);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (eventbox1), fixed4);

  entry_recherche_imen = gtk_entry_new ();
  gtk_widget_show (entry_recherche_imen);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_recherche_imen, 200, 248);
  gtk_widget_set_size_request (entry_recherche_imen, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_recherche_imen), 8226);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow2, 8, 344);
  gtk_widget_set_size_request (scrolledwindow2, 536, 240);

  treeview_equipement_imen = gtk_tree_view_new ();
  gtk_widget_show (treeview_equipement_imen);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview_equipement_imen);
  gtk_widget_set_size_request (treeview_equipement_imen, 300, 200);

  label56 = gtk_label_new (_("Liste des equipements :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed4), label56, 8, 296);
  gtk_widget_set_size_request (label56, 168, 40);

  label74 = gtk_label_new (_("Nom/ID equipment:"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed4), label74, 40, 248);
  gtk_widget_set_size_request (label74, 160, 32);

  label51 = gtk_label_new_with_mnemonic (_(" Rechercher:"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed4), label51, 40, 184);
  gtk_widget_set_size_request (label51, 160, 40);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_SMALL_TOOLBAR);
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed4), image13, 24, 184);
  gtk_widget_set_size_request (image13, 40, 40);

  label32 = gtk_label_new (_("Rechercher un equipement"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 152, 32);
  gtk_widget_set_size_request (label32, 200, 40);

  button_rechercher = gtk_button_new ();
  gtk_widget_show (button_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed4), button_rechercher, 376, 248);
  gtk_widget_set_size_request (button_rechercher, 64, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_rechercher), alignment16);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox13), label52, FALSE, FALSE, 0);

  recherche_modifier = gtk_button_new ();
  gtk_widget_show (recherche_modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), recherche_modifier, 168, 592);
  gtk_widget_set_size_request (recherche_modifier, 96, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (recherche_modifier), alignment20);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox17);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox17), image21, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox17), label73, FALSE, FALSE, 0);

  button_annuler = gtk_button_new ();
  gtk_widget_show (button_annuler);
  gtk_fixed_put (GTK_FIXED (fixed4), button_annuler, 304, 592);
  gtk_widget_set_size_request (button_annuler, 104, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button_annuler), alignment23);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox20);

  image24 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox20), image24, FALSE, FALSE, 0);

  label81 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox20), label81, FALSE, FALSE, 0);

  checkbutton_disponible = gtk_check_button_new_with_mnemonic (_("disponible"));
  gtk_widget_show (checkbutton_disponible);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton_disponible, 200, 152);
  gtk_widget_set_size_request (checkbutton_disponible, 118, 24);

  checkbutton_reserver_equi = gtk_check_button_new_with_mnemonic (_("r\303\251serv\303\251"));
  gtk_widget_show (checkbutton_reserver_equi);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton_reserver_equi, 200, 184);
  gtk_widget_set_size_request (checkbutton_reserver_equi, 118, 24);

  checkbutton_maintenance = gtk_check_button_new_with_mnemonic (_("en maintenance"));
  gtk_widget_show (checkbutton_maintenance);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton_maintenance, 200, 208);
  gtk_widget_set_size_request (checkbutton_maintenance, 118, 24);

  g_signal_connect ((gpointer) window_rechercher, "show",
                    G_CALLBACK (on_window_rechercher_show),
                    NULL);
  g_signal_connect ((gpointer) treeview_equipement_imen, "cursor_changed",
                    G_CALLBACK (on_treeview_equipement_imen_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) button_rechercher, "clicked",
                    G_CALLBACK (on_button_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) recherche_modifier, "clicked",
                    G_CALLBACK (on_recherche_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_annuler, "clicked",
                    G_CALLBACK (on_button_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_disponible, "toggled",
                    G_CALLBACK (on_checkbutton_disponible_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_reserver_equi, "toggled",
                    G_CALLBACK (on_checkbutton_reserver_equi_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_maintenance, "toggled",
                    G_CALLBACK (on_checkbutton_maintenance_toggled),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label51), checkbutton_reserver_equi);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_rechercher, window_rechercher, "window_rechercher");
  GLADE_HOOKUP_OBJECT (window_rechercher, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_rechercher, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window_rechercher, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window_rechercher, entry_recherche_imen, "entry_recherche_imen");
  GLADE_HOOKUP_OBJECT (window_rechercher, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window_rechercher, treeview_equipement_imen, "treeview_equipement_imen");
  GLADE_HOOKUP_OBJECT (window_rechercher, label56, "label56");
  GLADE_HOOKUP_OBJECT (window_rechercher, label74, "label74");
  GLADE_HOOKUP_OBJECT (window_rechercher, label51, "label51");
  GLADE_HOOKUP_OBJECT (window_rechercher, image13, "image13");
  GLADE_HOOKUP_OBJECT (window_rechercher, label32, "label32");
  GLADE_HOOKUP_OBJECT (window_rechercher, button_rechercher, "button_rechercher");
  GLADE_HOOKUP_OBJECT (window_rechercher, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window_rechercher, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window_rechercher, image14, "image14");
  GLADE_HOOKUP_OBJECT (window_rechercher, label52, "label52");
  GLADE_HOOKUP_OBJECT (window_rechercher, recherche_modifier, "recherche_modifier");
  GLADE_HOOKUP_OBJECT (window_rechercher, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window_rechercher, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window_rechercher, image21, "image21");
  GLADE_HOOKUP_OBJECT (window_rechercher, label73, "label73");
  GLADE_HOOKUP_OBJECT (window_rechercher, button_annuler, "button_annuler");
  GLADE_HOOKUP_OBJECT (window_rechercher, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window_rechercher, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window_rechercher, image24, "image24");
  GLADE_HOOKUP_OBJECT (window_rechercher, label81, "label81");
  GLADE_HOOKUP_OBJECT (window_rechercher, checkbutton_disponible, "checkbutton_disponible");
  GLADE_HOOKUP_OBJECT (window_rechercher, checkbutton_reserver_equi, "checkbutton_reserver_equi");
  GLADE_HOOKUP_OBJECT (window_rechercher, checkbutton_maintenance, "checkbutton_maintenance");

  return window_rechercher;
}

GtkWidget*
create_window_modifier (void)
{
  GtkWidget *window_modifier;
  GtkWidget *fixed5;
  GtkWidget *label16;
  GtkWidget *label9;
  GtkWidget *label4;
  GtkObject *spinbutton_modifier_Quantite_adj;
  GtkWidget *spinbutton_modifier_Quantite;
  GtkWidget *label7;
  GtkWidget *label54;
  GtkWidget *label76;
  GtkWidget *entry_modifier_centre;
  GtkWidget *entry_modifier_Nom;
  GtkWidget *entry_modifier_Categorie;
  GtkWidget *radio_reserve;
  GSList *radio_reserve_group = NULL;
  GtkWidget *radio_disponible;
  GtkWidget *radio_maintenance;
  GtkWidget *button_enregistrer_modifier;
  GtkWidget *alignment6;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label14;
  GtkWidget *button_annuler_modifier;
  GtkWidget *alignment25;
  GtkWidget *hbox22;
  GtkWidget *image26;
  GtkWidget *label83;

  window_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_modifier), _("modifier"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window_modifier), fixed5);

  label16 = gtk_label_new (_("Modifer un equipement"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed5), label16, 144, 8);
  gtk_widget_set_size_request (label16, 184, 40);

  label9 = gtk_label_new (_("Nouvelle quantite:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed5), label9, 0, 200);
  gtk_widget_set_size_request (label9, 168, 40);

  label4 = gtk_label_new (_("Nouveau nom:"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed5), label4, 0, 120);
  gtk_widget_set_size_request (label4, 144, 40);
  gtk_misc_set_alignment (GTK_MISC (label4), 0.45, 0.5);

  spinbutton_modifier_Quantite_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_modifier_Quantite = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_modifier_Quantite_adj), 1, 0);
  gtk_widget_show (spinbutton_modifier_Quantite);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_modifier_Quantite, 184, 208);
  gtk_widget_set_size_request (spinbutton_modifier_Quantite, 60, 27);

  label7 = gtk_label_new (_("Nouvelle categorie:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 0, 160);
  gtk_widget_set_size_request (label7, 168, 40);

  label54 = gtk_label_new (_("etats:"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed5), label54, 40, 280);
  gtk_widget_set_size_request (label54, 49, 17);

  label76 = gtk_label_new (_("centre :"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed5), label76, 24, 248);
  gtk_widget_set_size_request (label76, 120, 16);

  entry_modifier_centre = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_modifier_centre);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_modifier_centre, 160, 248);
  gtk_widget_set_size_request (entry_modifier_centre, 165, 24);

  entry_modifier_Nom = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_modifier_Nom);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_modifier_Nom, 160, 128);
  gtk_widget_set_size_request (entry_modifier_Nom, 165, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Halt\303\250res"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Barres et poids"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Machines guid\303\251es"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Bancs de musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Kettlebells"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Cages \303\240 squat"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Cordes de bataille"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Tapis de course"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("V\303\251lo elliptique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("V\303\251lo d\342\200\231appartement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Rameur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Stepper"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("SkiErg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Accessoires et petits \303\251quipements"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Tapis de sol ou tapis de yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Ballons suisses / ballons de stabilit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("M\303\251decine balls"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Corde \303\240 sauter"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("\303\211lastiques de r\303\251sistance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Step platform"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Rouleaux de massage / foam roller"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("TRX"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Pneus pour le flipping"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Sacs de sable"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Sled"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Nom), _("Barres de traction / dip station"));

  entry_modifier_Categorie = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_modifier_Categorie);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_modifier_Categorie, 160, 168);
  gtk_widget_set_size_request (entry_modifier_Categorie, 165, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Categorie), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Categorie), _("Cardio"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Categorie), _("Accessoires et petits \303\251quipements"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_modifier_Categorie), _("\303\211quipements fonctionnels / CrossFit"));

  radio_reserve = gtk_radio_button_new_with_mnemonic (NULL, _("reserve"));
  gtk_widget_show (radio_reserve);
  gtk_fixed_put (GTK_FIXED (fixed5), radio_reserve, 136, 288);
  gtk_widget_set_size_request (radio_reserve, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_reserve), radio_reserve_group);
  radio_reserve_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_reserve));

  radio_disponible = gtk_radio_button_new_with_mnemonic (NULL, _("disponible"));
  gtk_widget_show (radio_disponible);
  gtk_fixed_put (GTK_FIXED (fixed5), radio_disponible, 136, 328);
  gtk_widget_set_size_request (radio_disponible, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_disponible), radio_reserve_group);
  radio_reserve_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_disponible));

  radio_maintenance = gtk_radio_button_new_with_mnemonic (NULL, _("maintenance"));
  gtk_widget_show (radio_maintenance);
  gtk_fixed_put (GTK_FIXED (fixed5), radio_maintenance, 136, 360);
  gtk_widget_set_size_request (radio_maintenance, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_maintenance), radio_reserve_group);
  radio_reserve_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_maintenance));

  button_enregistrer_modifier = gtk_button_new ();
  gtk_widget_show (button_enregistrer_modifier);
  gtk_fixed_put (GTK_FIXED (fixed5), button_enregistrer_modifier, 72, 456);
  gtk_widget_set_size_request (button_enregistrer_modifier, 168, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_enregistrer_modifier), alignment6);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox3), label14, FALSE, FALSE, 0);

  button_annuler_modifier = gtk_button_new ();
  gtk_widget_show (button_annuler_modifier);
  gtk_fixed_put (GTK_FIXED (fixed5), button_annuler_modifier, 256, 456);
  gtk_widget_set_size_request (button_annuler_modifier, 162, 40);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button_annuler_modifier), alignment25);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox22);

  image26 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox22), image26, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox22), label83, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radio_reserve, "toggled",
                    G_CALLBACK (on_radio_reserve_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_disponible, "toggled",
                    G_CALLBACK (on_radio_disponible_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_maintenance, "toggled",
                    G_CALLBACK (on_radio_maintenance_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_enregistrer_modifier, "clicked",
                    G_CALLBACK (on_button_enregistrer_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_annuler_modifier, "clicked",
                    G_CALLBACK (on_button_annuler_modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_modifier, window_modifier, "window_modifier");
  GLADE_HOOKUP_OBJECT (window_modifier, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_modifier, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_modifier, label9, "label9");
  GLADE_HOOKUP_OBJECT (window_modifier, label4, "label4");
  GLADE_HOOKUP_OBJECT (window_modifier, spinbutton_modifier_Quantite, "spinbutton_modifier_Quantite");
  GLADE_HOOKUP_OBJECT (window_modifier, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_modifier, label54, "label54");
  GLADE_HOOKUP_OBJECT (window_modifier, label76, "label76");
  GLADE_HOOKUP_OBJECT (window_modifier, entry_modifier_centre, "entry_modifier_centre");
  GLADE_HOOKUP_OBJECT (window_modifier, entry_modifier_Nom, "entry_modifier_Nom");
  GLADE_HOOKUP_OBJECT (window_modifier, entry_modifier_Categorie, "entry_modifier_Categorie");
  GLADE_HOOKUP_OBJECT (window_modifier, radio_reserve, "radio_reserve");
  GLADE_HOOKUP_OBJECT (window_modifier, radio_disponible, "radio_disponible");
  GLADE_HOOKUP_OBJECT (window_modifier, radio_maintenance, "radio_maintenance");
  GLADE_HOOKUP_OBJECT (window_modifier, button_enregistrer_modifier, "button_enregistrer_modifier");
  GLADE_HOOKUP_OBJECT (window_modifier, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window_modifier, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_modifier, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_modifier, label14, "label14");
  GLADE_HOOKUP_OBJECT (window_modifier, button_annuler_modifier, "button_annuler_modifier");
  GLADE_HOOKUP_OBJECT (window_modifier, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window_modifier, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window_modifier, image26, "image26");
  GLADE_HOOKUP_OBJECT (window_modifier, label83, "label83");

  return window_modifier;
}

GtkWidget*
create_window_supprimer (void)
{
  GtkWidget *window_supprimer;
  GtkWidget *fixed7;
  GtkWidget *entryID_a_supp;
  GtkWidget *label13;
  GtkWidget *label64;
  GtkWidget *check_attention_supprimer;
  GtkWidget *alignment19;
  GtkWidget *hbox16;
  GtkWidget *image20;
  GtkWidget *label60;
  GtkWidget *button_supprimer_retour;
  GtkWidget *alignment26;
  GtkWidget *hbox23;
  GtkWidget *image27;
  GtkWidget *label84;
  GtkWidget *button_supprimer_imen;
  GtkWidget *alignment4;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label11;

  window_supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_supprimer), _("supprimer"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window_supprimer), fixed7);

  entryID_a_supp = gtk_entry_new ();
  gtk_widget_show (entryID_a_supp);
  gtk_fixed_put (GTK_FIXED (fixed7), entryID_a_supp, 112, 88);
  gtk_widget_set_size_request (entryID_a_supp, 184, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID_a_supp), 8226);

  label13 = gtk_label_new (_("Supprimer un equipement"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed7), label13, 88, 16);
  gtk_widget_set_size_request (label13, 208, 56);

  label64 = gtk_label_new (_("ID"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed7), label64, 40, 88);
  gtk_widget_set_size_request (label64, 88, 24);

  check_attention_supprimer = gtk_check_button_new ();
  gtk_widget_show (check_attention_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed7), check_attention_supprimer, 16, 136);
  gtk_widget_set_size_request (check_attention_supprimer, 368, 24);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (check_attention_supprimer), alignment19);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox16);

  image20 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox16), image20, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Attention !! Cette action est irreversible !!"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox16), label60, FALSE, FALSE, 0);

  button_supprimer_retour = gtk_button_new ();
  gtk_widget_show (button_supprimer_retour);
  gtk_fixed_put (GTK_FIXED (fixed7), button_supprimer_retour, 208, 192);
  gtk_widget_set_size_request (button_supprimer_retour, 120, 32);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button_supprimer_retour), alignment26);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox23);

  image27 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox23), image27, FALSE, FALSE, 0);

  label84 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox23), label84, FALSE, FALSE, 0);

  button_supprimer_imen = gtk_button_new ();
  gtk_widget_show (button_supprimer_imen);
  gtk_fixed_put (GTK_FIXED (fixed7), button_supprimer_imen, 56, 192);
  gtk_widget_set_size_request (button_supprimer_imen, 120, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_supprimer_imen), alignment4);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox1), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) check_attention_supprimer, "toggled",
                    G_CALLBACK (on_check_attention_supprimer_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_retour, "clicked",
                    G_CALLBACK (on_button_supprimer_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_imen, "clicked",
                    G_CALLBACK (on_button_supprimer_imen_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_supprimer, window_supprimer, "window_supprimer");
  GLADE_HOOKUP_OBJECT (window_supprimer, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window_supprimer, entryID_a_supp, "entryID_a_supp");
  GLADE_HOOKUP_OBJECT (window_supprimer, label13, "label13");
  GLADE_HOOKUP_OBJECT (window_supprimer, label64, "label64");
  GLADE_HOOKUP_OBJECT (window_supprimer, check_attention_supprimer, "check_attention_supprimer");
  GLADE_HOOKUP_OBJECT (window_supprimer, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window_supprimer, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window_supprimer, image20, "image20");
  GLADE_HOOKUP_OBJECT (window_supprimer, label60, "label60");
  GLADE_HOOKUP_OBJECT (window_supprimer, button_supprimer_retour, "button_supprimer_retour");
  GLADE_HOOKUP_OBJECT (window_supprimer, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window_supprimer, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window_supprimer, image27, "image27");
  GLADE_HOOKUP_OBJECT (window_supprimer, label84, "label84");
  GLADE_HOOKUP_OBJECT (window_supprimer, button_supprimer_imen, "button_supprimer_imen");
  GLADE_HOOKUP_OBJECT (window_supprimer, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_supprimer, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_supprimer, image1, "image1");
  GLADE_HOOKUP_OBJECT (window_supprimer, label11, "label11");

  return window_supprimer;
}

GtkWidget*
create_window_ajouter (void)
{
  GtkWidget *window_ajouter;
  GtkWidget *fixed8;
  GtkWidget *label20;
  GtkObject *spinbutton_ajouter_quantite_adj;
  GtkWidget *spinbutton_ajouter_quantite;
  GtkWidget *label42;
  GtkWidget *label27;
  GtkWidget *label19;
  GtkWidget *label17;
  GtkWidget *label75;
  GtkWidget *entry_ajouter_categorie;
  GtkWidget *combobox_centre;
  GtkWidget *radiobutton_reserver_equi;
  GSList *radiobutton_reserver_equi_group = NULL;
  GtkWidget *radio_disponible_equip;
  GtkWidget *radiobutton_maintenance_equi;
  GtkWidget *button_ajouter_enregistrer;
  GtkWidget *alignment21;
  GtkWidget *hbox18;
  GtkWidget *image22;
  GtkWidget *label79;
  GtkWidget *bouton_ajouter_retour;
  GtkWidget *alignment22;
  GtkWidget *hbox19;
  GtkWidget *image23;
  GtkWidget *label80;
  GtkWidget *entry_ajouter_nom;

  window_ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_ajouter), _("ajouter"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window_ajouter), fixed8);

  label20 = gtk_label_new (_("Categorie:"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed8), label20, 0, 160);
  gtk_widget_set_size_request (label20, 168, 40);
  gtk_misc_set_alignment (GTK_MISC (label20), 0.21, 0.5);

  spinbutton_ajouter_quantite_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton_ajouter_quantite = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_ajouter_quantite_adj), 1, 0);
  gtk_widget_show (spinbutton_ajouter_quantite);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton_ajouter_quantite, 200, 272);
  gtk_widget_set_size_request (spinbutton_ajouter_quantite, 60, 27);

  label42 = gtk_label_new (_("etat"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed8), label42, 56, 320);
  gtk_widget_set_size_request (label42, 80, 32);

  label27 = gtk_label_new (_("Quantite:"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed8), label27, 8, 248);
  gtk_widget_set_size_request (label27, 168, 40);
  gtk_misc_set_alignment (GTK_MISC (label27), 0.21, 0.5);

  label19 = gtk_label_new (_("Nom de l'equipement:"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed8), label19, 0, 128);
  gtk_widget_set_size_request (label19, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label19), 0.45, 0.5);

  label17 = gtk_label_new (_("Ajouter un equipement"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed8), label17, 144, 16);
  gtk_widget_set_size_request (label17, 184, 40);

  label75 = gtk_label_new (_("centre:"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed8), label75, 24, 208);
  gtk_widget_set_size_request (label75, 65, 33);

  entry_ajouter_categorie = gtk_combo_box_new_text ();
  gtk_widget_show (entry_ajouter_categorie);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_ajouter_categorie, 160, 168);
  gtk_widget_set_size_request (entry_ajouter_categorie, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_categorie), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_categorie), _("Cardio"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_categorie), _("Accessoires et petits \303\251quipements"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_categorie), _("\303\211quipements fonctionnels / CrossFit"));

  combobox_centre = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_centre);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox_centre, 160, 216);
  gtk_widget_set_size_request (combobox_centre, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_centre), _("energy fit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_centre), _("energy gym"));

  radiobutton_reserver_equi = gtk_radio_button_new_with_mnemonic (NULL, _("reserve"));
  gtk_widget_show (radiobutton_reserver_equi);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton_reserver_equi, 192, 320);
  gtk_widget_set_size_request (radiobutton_reserver_equi, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_reserver_equi), radiobutton_reserver_equi_group);
  radiobutton_reserver_equi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_reserver_equi));

  radio_disponible_equip = gtk_radio_button_new_with_mnemonic (NULL, _("disponible"));
  gtk_widget_show (radio_disponible_equip);
  gtk_fixed_put (GTK_FIXED (fixed8), radio_disponible_equip, 192, 360);
  gtk_widget_set_size_request (radio_disponible_equip, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_disponible_equip), radiobutton_reserver_equi_group);
  radiobutton_reserver_equi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_disponible_equip));

  radiobutton_maintenance_equi = gtk_radio_button_new_with_mnemonic (NULL, _("maintenance"));
  gtk_widget_show (radiobutton_maintenance_equi);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton_maintenance_equi, 192, 400);
  gtk_widget_set_size_request (radiobutton_maintenance_equi, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_maintenance_equi), radiobutton_reserver_equi_group);
  radiobutton_reserver_equi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_maintenance_equi));

  button_ajouter_enregistrer = gtk_button_new ();
  gtk_widget_show (button_ajouter_enregistrer);
  gtk_fixed_put (GTK_FIXED (fixed8), button_ajouter_enregistrer, 48, 448);
  gtk_widget_set_size_request (button_ajouter_enregistrer, 152, 40);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button_ajouter_enregistrer), alignment21);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox18);

  image22 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox18), image22, FALSE, FALSE, 0);

  label79 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox18), label79, FALSE, FALSE, 0);

  bouton_ajouter_retour = gtk_button_new ();
  gtk_widget_show (bouton_ajouter_retour);
  gtk_fixed_put (GTK_FIXED (fixed8), bouton_ajouter_retour, 232, 448);
  gtk_widget_set_size_request (bouton_ajouter_retour, 160, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (bouton_ajouter_retour), alignment22);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox19);

  image23 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox19), image23, FALSE, FALSE, 0);

  label80 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label80);
  gtk_box_pack_start (GTK_BOX (hbox19), label80, FALSE, FALSE, 0);

  entry_ajouter_nom = gtk_combo_box_new_text ();
  gtk_widget_show (entry_ajouter_nom);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_ajouter_nom, 160, 128);
  gtk_widget_set_size_request (entry_ajouter_nom, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Halt\303\250res"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Barres et poids"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Machines guid\303\251es"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Bancs de musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Kettlebells"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Cages \303\240 squat"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Cordes de bataille"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Tapis de course"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("V\303\251lo elliptique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("V\303\251lo d\342\200\231appartement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Rameur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Stepper"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("SkiErg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _(" roller"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("TRX"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Pneus pour le flipping"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Sacs de sable"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ajouter_nom), _("Sled"));

  g_signal_connect ((gpointer) radiobutton_reserver_equi, "toggled",
                    G_CALLBACK (on_radiobutton_reserver_equi_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_disponible_equip, "toggled",
                    G_CALLBACK (on_radio_disponible_equip_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_maintenance_equi, "toggled",
                    G_CALLBACK (on_radiobutton_maintenance_equi_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_enregistrer, "clicked",
                    G_CALLBACK (on_button_ajouter_enregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) bouton_ajouter_retour, "clicked",
                    G_CALLBACK (on_bouton_ajouter_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_ajouter, window_ajouter, "window_ajouter");
  GLADE_HOOKUP_OBJECT (window_ajouter, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window_ajouter, label20, "label20");
  GLADE_HOOKUP_OBJECT (window_ajouter, spinbutton_ajouter_quantite, "spinbutton_ajouter_quantite");
  GLADE_HOOKUP_OBJECT (window_ajouter, label42, "label42");
  GLADE_HOOKUP_OBJECT (window_ajouter, label27, "label27");
  GLADE_HOOKUP_OBJECT (window_ajouter, label19, "label19");
  GLADE_HOOKUP_OBJECT (window_ajouter, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_ajouter, label75, "label75");
  GLADE_HOOKUP_OBJECT (window_ajouter, entry_ajouter_categorie, "entry_ajouter_categorie");
  GLADE_HOOKUP_OBJECT (window_ajouter, combobox_centre, "combobox_centre");
  GLADE_HOOKUP_OBJECT (window_ajouter, radiobutton_reserver_equi, "radiobutton_reserver_equi");
  GLADE_HOOKUP_OBJECT (window_ajouter, radio_disponible_equip, "radio_disponible_equip");
  GLADE_HOOKUP_OBJECT (window_ajouter, radiobutton_maintenance_equi, "radiobutton_maintenance_equi");
  GLADE_HOOKUP_OBJECT (window_ajouter, button_ajouter_enregistrer, "button_ajouter_enregistrer");
  GLADE_HOOKUP_OBJECT (window_ajouter, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window_ajouter, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window_ajouter, image22, "image22");
  GLADE_HOOKUP_OBJECT (window_ajouter, label79, "label79");
  GLADE_HOOKUP_OBJECT (window_ajouter, bouton_ajouter_retour, "bouton_ajouter_retour");
  GLADE_HOOKUP_OBJECT (window_ajouter, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window_ajouter, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window_ajouter, image23, "image23");
  GLADE_HOOKUP_OBJECT (window_ajouter, label80, "label80");
  GLADE_HOOKUP_OBJECT (window_ajouter, entry_ajouter_nom, "entry_ajouter_nom");

  return window_ajouter;
}

GtkWidget*
create_window_reserver (void)
{
  GtkWidget *window_reserver;
  GtkWidget *fixed9;
  GtkWidget *label33;
  GtkObject *heure_res_adj;
  GtkWidget *heure_res;
  GtkObject *horaire_res_adj;
  GtkWidget *horaire_res;
  GtkWidget *id_entrain_res;
  GtkObject *quantite_adj;
  GtkWidget *quantite;
  GtkWidget *label86;
  GtkWidget *label38;
  GtkWidget *label35;
  GtkObject *min_res_adj;
  GtkWidget *min_res;
  GtkWidget *label65;
  GtkObject *jour_res_adj;
  GtkWidget *jour_res;
  GtkObject *mois_res_adj;
  GtkWidget *mois_res;
  GtkObject *annee_res_adj;
  GtkWidget *annee_res;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *label85;
  GtkWidget *label92;
  GtkWidget *label34;
  GtkWidget *label87;
  GtkWidget *label37;
  GtkObject *nb_salle_res_adj;
  GtkWidget *nb_salle_res;
  GtkWidget *label94;
  GtkWidget *label36;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview_reservation_equip;
  GtkWidget *reserver;
  GtkWidget *alignment12;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label39;
  GtkWidget *reset;
  GtkWidget *alignment18;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label59;
  GtkWidget *retour_reserver;
  GtkWidget *alignment27;
  GtkWidget *hbox24;
  GtkWidget *image28;
  GtkWidget *label93;
  GtkWidget *nom_entraineur_res;
  GtkWidget *nom_cours_res;
  GtkWidget *nom_centre_res;
  GtkWidget *nom_equip_res;

  window_reserver = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_reserver), _("reserver"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window_reserver), fixed9);

  label33 = gtk_label_new (_("Reserver un equipement:"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed9), label33, 104, 24);
  gtk_widget_set_size_request (label33, 176, 48);

  heure_res_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  heure_res = gtk_spin_button_new (GTK_ADJUSTMENT (heure_res_adj), 1, 0);
  gtk_widget_show (heure_res);
  gtk_fixed_put (GTK_FIXED (fixed9), heure_res, 168, 336);
  gtk_widget_set_size_request (heure_res, 60, 27);

  horaire_res_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  horaire_res = gtk_spin_button_new (GTK_ADJUSTMENT (horaire_res_adj), 1, 0);
  gtk_widget_show (horaire_res);
  gtk_fixed_put (GTK_FIXED (fixed9), horaire_res, 168, 376);
  gtk_widget_set_size_request (horaire_res, 60, 27);

  id_entrain_res = gtk_entry_new ();
  gtk_widget_show (id_entrain_res);
  gtk_fixed_put (GTK_FIXED (fixed9), id_entrain_res, 160, 160);
  gtk_widget_set_size_request (id_entrain_res, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_entrain_res), 8226);

  quantite_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  quantite = gtk_spin_button_new (GTK_ADJUSTMENT (quantite_adj), 1, 0);
  gtk_widget_show (quantite);
  gtk_fixed_put (GTK_FIXED (fixed9), quantite, 168, 120);
  gtk_widget_set_size_request (quantite, 60, 27);

  label86 = gtk_label_new (_("ID de l'entraineur :"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed9), label86, 8, 152);
  gtk_widget_set_size_request (label86, 168, 32);

  label38 = gtk_label_new (_("Nom Du Cours:"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed9), label38, 32, 240);
  gtk_widget_set_size_request (label38, 136, 40);

  label35 = gtk_label_new (_("Nom de l'entraineur:"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed9), label35, 16, 200);
  gtk_widget_set_size_request (label35, 136, 40);

  min_res_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  min_res = gtk_spin_button_new (GTK_ADJUSTMENT (min_res_adj), 1, 0);
  gtk_widget_show (min_res);
  gtk_fixed_put (GTK_FIXED (fixed9), min_res, 272, 336);
  gtk_widget_set_size_request (min_res, 60, 27);

  label65 = gtk_label_new (_("Date du cours:"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed9), label65, 40, 288);
  gtk_widget_set_size_request (label65, 128, 32);

  jour_res_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour_res = gtk_spin_button_new (GTK_ADJUSTMENT (jour_res_adj), 1, 0);
  gtk_widget_show (jour_res);
  gtk_fixed_put (GTK_FIXED (fixed9), jour_res, 168, 288);
  gtk_widget_set_size_request (jour_res, 60, 27);

  mois_res_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois_res = gtk_spin_button_new (GTK_ADJUSTMENT (mois_res_adj), 1, 0);
  gtk_widget_show (mois_res);
  gtk_fixed_put (GTK_FIXED (fixed9), mois_res, 256, 288);
  gtk_widget_set_size_request (mois_res, 60, 27);

  annee_res_adj = gtk_adjustment_new (1, 2000, 2025, 1, 10, 10);
  annee_res = gtk_spin_button_new (GTK_ADJUSTMENT (annee_res_adj), 1, 0);
  gtk_widget_show (annee_res);
  gtk_fixed_put (GTK_FIXED (fixed9), annee_res, 344, 288);
  gtk_widget_set_size_request (annee_res, 60, 27);

  label90 = gtk_label_new (_("/"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed9), label90, 216, 296);
  gtk_widget_set_size_request (label90, 49, 17);

  label91 = gtk_label_new (_("/"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed9), label91, 304, 296);
  gtk_widget_set_size_request (label91, 49, 17);

  label88 = gtk_label_new (_("hr"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed9), label88, 224, 328);
  gtk_widget_set_size_request (label88, 56, 40);

  label89 = gtk_label_new (_("min"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed9), label89, 328, 328);
  gtk_widget_set_size_request (label89, 56, 40);

  label85 = gtk_label_new (_("Nom du centre :"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed9), label85, 32, 424);
  gtk_widget_set_size_request (label85, 136, 24);

  label92 = gtk_label_new (_("Liste des reservations :"));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed9), label92, 8, 552);
  gtk_widget_set_size_request (label92, 200, 32);

  label34 = gtk_label_new (_("Nom de l'equipement:"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed9), label34, 0, 80);
  gtk_widget_set_size_request (label34, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label34), 0.45, 0.5);

  label87 = gtk_label_new (_("Quantit\303\251 r\303\251serv\303\251e :"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed9), label87, 0, 120);
  gtk_widget_set_size_request (label87, 176, 32);

  label37 = gtk_label_new (_("Dur\303\251e Du Cours:"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed9), label37, 32, 328);
  gtk_widget_set_size_request (label37, 136, 40);

  nb_salle_res_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  nb_salle_res = gtk_spin_button_new (GTK_ADJUSTMENT (nb_salle_res_adj), 1, 0);
  gtk_widget_show (nb_salle_res);
  gtk_fixed_put (GTK_FIXED (fixed9), nb_salle_res, 168, 464);
  gtk_widget_set_size_request (nb_salle_res, 60, 27);

  label94 = gtk_label_new (_(" Salle du Cours :"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed9), label94, 40, 456);
  gtk_widget_set_size_request (label94, 120, 40);

  label36 = gtk_label_new (_("Horaire Du Cours:"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed9), label36, 32, 368);
  gtk_widget_set_size_request (label36, 136, 40);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_fixed_put (GTK_FIXED (fixed9), scrolledwindow4, 8, 584);
  gtk_widget_set_size_request (scrolledwindow4, 584, 248);

  treeview_reservation_equip = gtk_tree_view_new ();
  gtk_widget_show (treeview_reservation_equip);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview_reservation_equip);
  gtk_widget_set_size_request (treeview_reservation_equip, 300, 200);

  reserver = gtk_button_new ();
  gtk_widget_show (reserver);
  gtk_fixed_put (GTK_FIXED (fixed9), reserver, 56, 504);
  gtk_widget_set_size_request (reserver, 128, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (reserver), alignment12);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox9), label39, FALSE, FALSE, 0);

  reset = gtk_button_new ();
  gtk_widget_show (reset);
  gtk_fixed_put (GTK_FIXED (fixed9), reset, 200, 504);
  gtk_widget_set_size_request (reset, 146, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (reset), alignment18);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Reset"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox15), label59, FALSE, FALSE, 0);

  retour_reserver = gtk_button_new ();
  gtk_widget_show (retour_reserver);
  gtk_fixed_put (GTK_FIXED (fixed9), retour_reserver, 360, 504);
  gtk_widget_set_size_request (retour_reserver, 136, 40);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (retour_reserver), alignment27);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox24);

  image28 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox24), image28, FALSE, FALSE, 0);

  label93 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox24), label93, FALSE, FALSE, 0);

  nom_entraineur_res = gtk_combo_box_entry_new_text ();
  gtk_widget_show (nom_entraineur_res);
  gtk_fixed_put (GTK_FIXED (fixed9), nom_entraineur_res, 160, 208);
  gtk_widget_set_size_request (nom_entraineur_res, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_entraineur_res), _("ali"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_entraineur_res), _("mohamed"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_entraineur_res), _("omar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_entraineur_res), _("chedlia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_entraineur_res), _("maissa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_entraineur_res), _("ines"));

  nom_cours_res = gtk_combo_box_entry_new_text ();
  gtk_widget_show (nom_cours_res);
  gtk_fixed_put (GTK_FIXED (fixed9), nom_cours_res, 160, 248);
  gtk_widget_set_size_request (nom_cours_res, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_cours_res), _("dance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_cours_res), _("caedio"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_cours_res), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_cours_res), _("zoumba"));

  nom_centre_res = gtk_combo_box_entry_new_text ();
  gtk_widget_show (nom_centre_res);
  gtk_fixed_put (GTK_FIXED (fixed9), nom_centre_res, 168, 424);
  gtk_widget_set_size_request (nom_centre_res, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_centre_res), _("california"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_centre_res), _("golden"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_centre_res), _("energy_fit"));

  nom_equip_res = gtk_combo_box_entry_new_text ();
  gtk_widget_show (nom_equip_res);
  gtk_fixed_put (GTK_FIXED (fixed9), nom_equip_res, 160, 80);
  gtk_widget_set_size_request (nom_equip_res, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Halt\303\250res"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Barres et poids"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Machines guid\303\251es"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Bancs de musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Kettlebells"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Cages \303\240 squat"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Cordes de bataille"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Tapis de course"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("V\303\251lo elliptique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("V\303\251lo d\342\200\231appartement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Rameur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Stepper"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("SkiErg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _(" roller"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("TRX"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Pneus pour le flipping"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Sacs de sable"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nom_equip_res), _("Sled"));

  g_signal_connect ((gpointer) window_reserver, "show",
                    G_CALLBACK (on_window_reserver_state_changed),
                    NULL);
  g_signal_connect ((gpointer) reserver, "clicked",
                    G_CALLBACK (on_reserver_clicked),
                    NULL);
  g_signal_connect ((gpointer) reset, "clicked",
                    G_CALLBACK (on_reset_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_reserver, "clicked",
                    G_CALLBACK (on_retour_reserver_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_reserver, window_reserver, "window_reserver");
  GLADE_HOOKUP_OBJECT (window_reserver, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window_reserver, label33, "label33");
  GLADE_HOOKUP_OBJECT (window_reserver, heure_res, "heure_res");
  GLADE_HOOKUP_OBJECT (window_reserver, horaire_res, "horaire_res");
  GLADE_HOOKUP_OBJECT (window_reserver, id_entrain_res, "id_entrain_res");
  GLADE_HOOKUP_OBJECT (window_reserver, quantite, "quantite");
  GLADE_HOOKUP_OBJECT (window_reserver, label86, "label86");
  GLADE_HOOKUP_OBJECT (window_reserver, label38, "label38");
  GLADE_HOOKUP_OBJECT (window_reserver, label35, "label35");
  GLADE_HOOKUP_OBJECT (window_reserver, min_res, "min_res");
  GLADE_HOOKUP_OBJECT (window_reserver, label65, "label65");
  GLADE_HOOKUP_OBJECT (window_reserver, jour_res, "jour_res");
  GLADE_HOOKUP_OBJECT (window_reserver, mois_res, "mois_res");
  GLADE_HOOKUP_OBJECT (window_reserver, annee_res, "annee_res");
  GLADE_HOOKUP_OBJECT (window_reserver, label90, "label90");
  GLADE_HOOKUP_OBJECT (window_reserver, label91, "label91");
  GLADE_HOOKUP_OBJECT (window_reserver, label88, "label88");
  GLADE_HOOKUP_OBJECT (window_reserver, label89, "label89");
  GLADE_HOOKUP_OBJECT (window_reserver, label85, "label85");
  GLADE_HOOKUP_OBJECT (window_reserver, label92, "label92");
  GLADE_HOOKUP_OBJECT (window_reserver, label34, "label34");
  GLADE_HOOKUP_OBJECT (window_reserver, label87, "label87");
  GLADE_HOOKUP_OBJECT (window_reserver, label37, "label37");
  GLADE_HOOKUP_OBJECT (window_reserver, nb_salle_res, "nb_salle_res");
  GLADE_HOOKUP_OBJECT (window_reserver, label94, "label94");
  GLADE_HOOKUP_OBJECT (window_reserver, label36, "label36");
  GLADE_HOOKUP_OBJECT (window_reserver, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (window_reserver, treeview_reservation_equip, "treeview_reservation_equip");
  GLADE_HOOKUP_OBJECT (window_reserver, reserver, "reserver");
  GLADE_HOOKUP_OBJECT (window_reserver, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window_reserver, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_reserver, image9, "image9");
  GLADE_HOOKUP_OBJECT (window_reserver, label39, "label39");
  GLADE_HOOKUP_OBJECT (window_reserver, reset, "reset");
  GLADE_HOOKUP_OBJECT (window_reserver, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window_reserver, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window_reserver, image19, "image19");
  GLADE_HOOKUP_OBJECT (window_reserver, label59, "label59");
  GLADE_HOOKUP_OBJECT (window_reserver, retour_reserver, "retour_reserver");
  GLADE_HOOKUP_OBJECT (window_reserver, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window_reserver, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window_reserver, image28, "image28");
  GLADE_HOOKUP_OBJECT (window_reserver, label93, "label93");
  GLADE_HOOKUP_OBJECT (window_reserver, nom_entraineur_res, "nom_entraineur_res");
  GLADE_HOOKUP_OBJECT (window_reserver, nom_cours_res, "nom_cours_res");
  GLADE_HOOKUP_OBJECT (window_reserver, nom_centre_res, "nom_centre_res");
  GLADE_HOOKUP_OBJECT (window_reserver, nom_equip_res, "nom_equip_res");

  return window_reserver;
}

GtkWidget*
create_window_dashboard (void)
{
  GtkWidget *window_dashboard;
  GtkWidget *fixed10;
  GtkWidget *image30;
  GtkWidget *label97;
  GtkWidget *retour;
  GtkWidget *alignment28;
  GtkWidget *hbox25;
  GtkWidget *image29;
  GtkWidget *label96;
  GtkWidget *administrateur;
  GtkWidget *entraineur;

  window_dashboard = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_dashboard), _("window1"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window_dashboard), fixed10);

  image30 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed10), image30, 0, 24);
  gtk_widget_set_size_request (image30, 72, 32);

  label97 = gtk_label_new (_("Continuer en tant qu'"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed10), label97, 0, 24);
  gtk_widget_set_size_request (label97, 240, 32);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed10), retour, 136, 216);
  gtk_widget_set_size_request (retour, 112, 48);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (retour), alignment28);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox25);

  image29 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox25), image29, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox25), label96, FALSE, FALSE, 0);

  administrateur = gtk_button_new_with_mnemonic (_("Administrateur"));
  gtk_widget_show (administrateur);
  gtk_fixed_put (GTK_FIXED (fixed10), administrateur, 80, 72);
  gtk_widget_set_size_request (administrateur, 216, 56);

  entraineur = gtk_button_new_with_mnemonic (_("Entraineur"));
  gtk_widget_show (entraineur);
  gtk_fixed_put (GTK_FIXED (fixed10), entraineur, 80, 144);
  gtk_widget_set_size_request (entraineur, 216, 56);

  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) administrateur, "clicked",
                    G_CALLBACK (on_administrateur_clicked),
                    NULL);
  g_signal_connect ((gpointer) entraineur, "clicked",
                    G_CALLBACK (on_entraineur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_dashboard, window_dashboard, "window_dashboard");
  GLADE_HOOKUP_OBJECT (window_dashboard, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window_dashboard, image30, "image30");
  GLADE_HOOKUP_OBJECT (window_dashboard, label97, "label97");
  GLADE_HOOKUP_OBJECT (window_dashboard, retour, "retour");
  GLADE_HOOKUP_OBJECT (window_dashboard, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window_dashboard, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window_dashboard, image29, "image29");
  GLADE_HOOKUP_OBJECT (window_dashboard, label96, "label96");
  GLADE_HOOKUP_OBJECT (window_dashboard, administrateur, "administrateur");
  GLADE_HOOKUP_OBJECT (window_dashboard, entraineur, "entraineur");

  return window_dashboard;
}

