/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_administrateur (void);
GtkWidget* create_window_rechercher (void);
GtkWidget* create_window_modifier (void);
GtkWidget* create_window_supprimer (void);
GtkWidget* create_window_ajouter (void);
GtkWidget* create_window_reserver (void);
GtkWidget* create_window_dashboard (void);
