/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
 /* GtkWidget *window_administrateur;
  GtkWidget *window_rechercher;
  GtkWidget *window_modifier;
  GtkWidget *window_supprimer;
  GtkWidget *window_ajouter;
  GtkWidget *window_reserver;*/
  GtkWidget *window_dashboard;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 /* window_administrateur = create_window_administrateur ();
  gtk_widget_show (window_administrateur);
  window_rechercher = create_window_rechercher ();
  gtk_widget_show (window_rechercher);
  window_modifier = create_window_modifier ();
  gtk_widget_show (window_modifier);
  window_supprimer = create_window_supprimer ();
  gtk_widget_show (window_supprimer);
  window_ajouter = create_window_ajouter ();
  gtk_widget_show (window_ajouter);
  window_reserver = create_window_reserver ();
  gtk_widget_show (window_reserver);*/
  window_dashboard = create_window_dashboard ();
  gtk_widget_show (window_dashboard);

  gtk_main ();
  return 0;
}

