/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create__administrateur (void)
{
  GtkWidget *_administrateur;
  GtkWidget *fixed2;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *alignment14;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label41;

  _administrateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (_administrateur), _("administrateur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (_administrateur), fixed2);

  button2 = gtk_button_new_with_mnemonic (_("ajouter un equipement"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 32, 32);
  gtk_widget_set_size_request (button2, 184, 48);

  button3 = gtk_button_new_with_mnemonic (_("modifier un equipement"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 32, 96);
  gtk_widget_set_size_request (button3, 184, 48);

  button4 = gtk_button_new_with_mnemonic (_("supprimer un equipement"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 32, 160);
  gtk_widget_set_size_request (button4, 184, 48);

  button5 = gtk_button_new_with_mnemonic (_("rechercher un equipement"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 32, 224);
  gtk_widget_set_size_request (button5, 184, 48);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 264, 192);
  gtk_widget_set_size_request (button6, 112, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button6), alignment14);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox11), label41, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (_administrateur, _administrateur, "_administrateur");
  GLADE_HOOKUP_OBJECT (_administrateur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (_administrateur, button2, "button2");
  GLADE_HOOKUP_OBJECT (_administrateur, button3, "button3");
  GLADE_HOOKUP_OBJECT (_administrateur, button4, "button4");
  GLADE_HOOKUP_OBJECT (_administrateur, button5, "button5");
  GLADE_HOOKUP_OBJECT (_administrateur, button6, "button6");
  GLADE_HOOKUP_OBJECT (_administrateur, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (_administrateur, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (_administrateur, image11, "image11");
  GLADE_HOOKUP_OBJECT (_administrateur, label41, "label41");

  return _administrateur;
}

GtkWidget*
create_rechercher (void)
{
  GtkWidget *rechercher;
  GtkWidget *alignment1;
  GtkWidget *eventbox1;
  GtkWidget *fixed4;
  GtkWidget *label32;
  GtkWidget *entry16;
  GtkWidget *entry17;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *comboboxentry3;
  GtkWidget *label30;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label50;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton5;
  GtkWidget *label51;
  GtkWidget *image13;
  GtkWidget *label56;
  GtkWidget *treeview2;
  GtkWidget *button18;
  GtkWidget *alignment17;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label53;
  GtkWidget *button13;
  GtkWidget *alignment16;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label52;

  rechercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (rechercher), _("rechercher"));
  gtk_window_set_default_size (GTK_WINDOW (rechercher), 4, 100);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (rechercher), alignment1);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), eventbox1);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (eventbox1), fixed4);

  label32 = gtk_label_new (_("Rechercher un equipement"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 152, 32);
  gtk_widget_set_size_request (label32, 200, 40);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed4), entry16, 176, 176);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed4), entry17, 176, 216);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  label24 = gtk_label_new (_("ID:"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 32, 176);
  gtk_widget_set_size_request (label24, 104, 48);

  label25 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 48, 216);
  gtk_widget_set_size_request (label25, 81, 32);

  label26 = gtk_label_new (_("Categorie:"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 48, 248);
  gtk_widget_set_size_request (label26, 168, 40);
  gtk_misc_set_alignment (GTK_MISC (label26), 0.21, 0.5);

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxentry3, 176, 256);
  gtk_widget_set_size_request (comboboxentry3, 157, 24);

  label30 = gtk_label_new (_("Quantite:"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 48, 288);
  gtk_widget_set_size_request (label30, 168, 40);
  gtk_misc_set_alignment (GTK_MISC (label30), 0.21, 0.5);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 208, 296);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  label50 = gtk_label_new (_("etats:"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed4), label50, 64, 344);
  gtk_widget_set_size_request (label50, 73, 24);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("reserve"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton4, 184, 344);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("disponible"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton6, 184, 392);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("maintenance"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton5, 184, 368);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  label51 = gtk_label_new_with_mnemonic (_("Filtre de Rechercher:"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed4), label51, 72, 104);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_SMALL_TOOLBAR);
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed4), image13, 32, 104);

  label56 = gtk_label_new (_("Liste des equipement:"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed4), label56, 40, 464);
  gtk_widget_set_size_request (label56, 168, 40);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview2, 152, 520);
  gtk_widget_set_size_request (treeview2, 300, 200);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed4), button18, 456, 304);
  gtk_widget_set_size_request (button18, 104, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button18), alignment17);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox14), label53, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed4), button13, 456, 240);
  gtk_widget_set_size_request (button13, 104, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button13), alignment16);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox13), label52, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rechercher, rechercher, "rechercher");
  GLADE_HOOKUP_OBJECT (rechercher, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (rechercher, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (rechercher, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (rechercher, label32, "label32");
  GLADE_HOOKUP_OBJECT (rechercher, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (rechercher, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (rechercher, label24, "label24");
  GLADE_HOOKUP_OBJECT (rechercher, label25, "label25");
  GLADE_HOOKUP_OBJECT (rechercher, label26, "label26");
  GLADE_HOOKUP_OBJECT (rechercher, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (rechercher, label30, "label30");
  GLADE_HOOKUP_OBJECT (rechercher, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (rechercher, label50, "label50");
  GLADE_HOOKUP_OBJECT (rechercher, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (rechercher, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (rechercher, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (rechercher, label51, "label51");
  GLADE_HOOKUP_OBJECT (rechercher, image13, "image13");
  GLADE_HOOKUP_OBJECT (rechercher, label56, "label56");
  GLADE_HOOKUP_OBJECT (rechercher, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (rechercher, button18, "button18");
  GLADE_HOOKUP_OBJECT (rechercher, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (rechercher, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (rechercher, image15, "image15");
  GLADE_HOOKUP_OBJECT (rechercher, label53, "label53");
  GLADE_HOOKUP_OBJECT (rechercher, button13, "button13");
  GLADE_HOOKUP_OBJECT (rechercher, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (rechercher, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (rechercher, image14, "image14");
  GLADE_HOOKUP_OBJECT (rechercher, label52, "label52");

  return rechercher;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed5;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *label16;
  GtkWidget *label6;
  GtkWidget *label9;
  GtkWidget *label4;
  GtkWidget *label7;
  GtkWidget *comboboxentry4;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label54;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton9;
  GtkWidget *button7;
  GtkWidget *alignment6;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label14;
  GtkWidget *button8;
  GtkWidget *alignment7;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label15;
  GtkWidget *image16;
  GtkWidget *label55;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("modifier"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (modifier), fixed5);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed5), entry2, 160, 128);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed5), entry3, 160, 88);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label16 = gtk_label_new (_("Modifer un equipement"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed5), label16, 144, 8);
  gtk_widget_set_size_request (label16, 184, 40);

  label6 = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed5), label6, 0, 80);
  gtk_widget_set_size_request (label6, 184, 48);
  gtk_misc_set_alignment (GTK_MISC (label6), 0.21, 0.5);

  label9 = gtk_label_new (_("Nouvelle quantite:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed5), label9, 0, 200);
  gtk_widget_set_size_request (label9, 168, 40);

  label4 = gtk_label_new (_("Nouveau nom:"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed5), label4, 0, 120);
  gtk_widget_set_size_request (label4, 144, 40);
  gtk_misc_set_alignment (GTK_MISC (label4), 0.45, 0.5);

  label7 = gtk_label_new (_("Nouvelle categorie:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 0, 160);
  gtk_widget_set_size_request (label7, 168, 40);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentry4, 160, 168);
  gtk_widget_set_size_request (comboboxentry4, 157, 24);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton3, 176, 200);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label54 = gtk_label_new (_("etats:"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed5), label54, 40, 248);
  gtk_widget_set_size_request (label54, 49, 17);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("reserve"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton7, 136, 256);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("disponible"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton8, 136, 296);
  gtk_widget_set_size_request (radiobutton8, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, _("maintenance"));
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton9, 136, 336);
  gtk_widget_set_size_request (radiobutton9, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 80, 424);
  gtk_widget_set_size_request (button7, 168, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button7), alignment6);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox3), label14, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed5), button8, 272, 424);
  gtk_widget_set_size_request (button8, 162, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button8), alignment7);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);

  image16 = create_pixmap (modifier, NULL);
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed5), image16, 160, 504);
  gtk_widget_set_size_request (image16, 208, 112);

  label55 = gtk_label_new (_("Image:"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed5), label55, 32, 488);
  gtk_widget_set_size_request (label55, 80, 48);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (modifier, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (modifier, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (modifier, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier, label6, "label6");
  GLADE_HOOKUP_OBJECT (modifier, label9, "label9");
  GLADE_HOOKUP_OBJECT (modifier, label4, "label4");
  GLADE_HOOKUP_OBJECT (modifier, label7, "label7");
  GLADE_HOOKUP_OBJECT (modifier, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (modifier, label54, "label54");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (modifier, button7, "button7");
  GLADE_HOOKUP_OBJECT (modifier, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modifier, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (modifier, image3, "image3");
  GLADE_HOOKUP_OBJECT (modifier, label14, "label14");
  GLADE_HOOKUP_OBJECT (modifier, button8, "button8");
  GLADE_HOOKUP_OBJECT (modifier, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifier, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (modifier, image4, "image4");
  GLADE_HOOKUP_OBJECT (modifier, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier, image16, "image16");
  GLADE_HOOKUP_OBJECT (modifier, label55, "label55");

  return modifier;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixed7;
  GtkWidget *label13;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *treeview1;
  GtkWidget *comboboxentry2;
  GtkWidget *button10;
  GtkWidget *alignment5;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label12;
  GtkWidget *button9;
  GtkWidget *alignment4;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label11;
  GtkWidget *checkbutton1;
  GtkWidget *image17;
  GtkWidget *label57;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer), _("supprimer"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (supprimer), fixed7);

  label13 = gtk_label_new (_("Supprimer un equipement"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed7), label13, 80, 24);
  gtk_widget_set_size_request (label13, 208, 56);

  label46 = gtk_label_new (_("selection:"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed7), label46, 0, 96);
  gtk_widget_set_size_request (label46, 168, 16);

  label47 = gtk_label_new (_("details:"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed7), label47, 48, 136);
  gtk_widget_set_size_request (label47, 72, 24);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview1, 136, 136);
  gtk_widget_set_size_request (treeview1, 300, 200);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxentry2, 136, 88);
  gtk_widget_set_size_request (comboboxentry2, 189, 29);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed7), button10, 264, 448);
  gtk_widget_set_size_request (button10, 120, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button10), alignment5);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed7), button9, 112, 448);
  gtk_widget_set_size_request (button9, 120, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button9), alignment4);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox1), label11, FALSE, FALSE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Attention !! Cette action est irreversible !!"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbutton1, 48, 368);
  gtk_widget_set_size_request (checkbutton1, 368, 24);

  image17 = create_pixmap (supprimer, NULL);
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed7), image17, 160, 568);
  gtk_widget_set_size_request (image17, 149, 80);

  label57 = gtk_label_new (_("Image:"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed7), label57, 32, 520);
  gtk_widget_set_size_request (label57, 80, 48);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (supprimer, label13, "label13");
  GLADE_HOOKUP_OBJECT (supprimer, label46, "label46");
  GLADE_HOOKUP_OBJECT (supprimer, label47, "label47");
  GLADE_HOOKUP_OBJECT (supprimer, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (supprimer, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (supprimer, button10, "button10");
  GLADE_HOOKUP_OBJECT (supprimer, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (supprimer, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (supprimer, image2, "image2");
  GLADE_HOOKUP_OBJECT (supprimer, label12, "label12");
  GLADE_HOOKUP_OBJECT (supprimer, button9, "button9");
  GLADE_HOOKUP_OBJECT (supprimer, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (supprimer, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (supprimer, image1, "image1");
  GLADE_HOOKUP_OBJECT (supprimer, label11, "label11");
  GLADE_HOOKUP_OBJECT (supprimer, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (supprimer, image17, "image17");
  GLADE_HOOKUP_OBJECT (supprimer, label57, "label57");

  return supprimer;
}

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixed8;
  GtkWidget *label18;
  GtkWidget *entry7;
  GtkWidget *entry9;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *label17;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *comboboxentry1;
  GtkWidget *label42;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *label27;
  GtkWidget *button17;
  GtkWidget *alignment15;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label49;
  GtkWidget *button12;
  GtkWidget *alignment9;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label23;
  GtkWidget *label58;
  GtkWidget *image18;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter), _("ajouter"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (ajouter), fixed8);

  label18 = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed8), label18, 0, 88);
  gtk_widget_set_size_request (label18, 184, 48);
  gtk_misc_set_alignment (GTK_MISC (label18), 0.21, 0.5);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed8), entry7, 160, 88);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed8), entry9, 160, 128);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  label20 = gtk_label_new (_("Categorie:"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed8), label20, 0, 160);
  gtk_widget_set_size_request (label20, 168, 40);
  gtk_misc_set_alignment (GTK_MISC (label20), 0.21, 0.5);

  label19 = gtk_label_new (_("Nom de l'equipement:"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed8), label19, 0, 128);
  gtk_widget_set_size_request (label19, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label19), 0.45, 0.5);

  label17 = gtk_label_new (_("Ajouter un equipement"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed8), label17, 152, 16);
  gtk_widget_set_size_request (label17, 184, 40);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton1, 192, 208);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry1, 160, 168);
  gtk_widget_set_size_request (comboboxentry1, 165, 32);

  label42 = gtk_label_new (_("etat"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed8), label42, 8, 256);
  gtk_widget_set_size_request (label42, 80, 32);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("reserve"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton1, 200, 256);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("disponible"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton2, 200, 288);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("maintenance"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton3, 200, 328);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label27 = gtk_label_new (_("Quantite:"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed8), label27, 0, 200);
  gtk_widget_set_size_request (label27, 168, 40);
  gtk_misc_set_alignment (GTK_MISC (label27), 0.21, 0.5);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed8), button17, 64, 416);
  gtk_widget_set_size_request (button17, 152, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button17), alignment15);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("enregistrer"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox12), label49, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed8), button12, 256, 416);
  gtk_widget_set_size_request (button12, 160, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button12), alignment9);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox6), label23, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0.5, 0);
  gtk_misc_set_padding (GTK_MISC (label23), 23, 0);

  label58 = gtk_label_new (_("Image:"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed8), label58, 32, 488);
  gtk_widget_set_size_request (label58, 80, 48);

  image18 = create_pixmap (ajouter, NULL);
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed8), image18, 168, 552);
  gtk_widget_set_size_request (image18, 152, 104);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (ajouter, label18, "label18");
  GLADE_HOOKUP_OBJECT (ajouter, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (ajouter, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (ajouter, label20, "label20");
  GLADE_HOOKUP_OBJECT (ajouter, label19, "label19");
  GLADE_HOOKUP_OBJECT (ajouter, label17, "label17");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajouter, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (ajouter, label42, "label42");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (ajouter, label27, "label27");
  GLADE_HOOKUP_OBJECT (ajouter, button17, "button17");
  GLADE_HOOKUP_OBJECT (ajouter, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (ajouter, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (ajouter, image12, "image12");
  GLADE_HOOKUP_OBJECT (ajouter, label49, "label49");
  GLADE_HOOKUP_OBJECT (ajouter, button12, "button12");
  GLADE_HOOKUP_OBJECT (ajouter, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (ajouter, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajouter, image6, "image6");
  GLADE_HOOKUP_OBJECT (ajouter, label23, "label23");
  GLADE_HOOKUP_OBJECT (ajouter, label58, "label58");
  GLADE_HOOKUP_OBJECT (ajouter, image18, "image18");

  return ajouter;
}

GtkWidget*
create_entraineur (void)
{
  GtkWidget *entraineur;
  GtkWidget *fixed9;
  GtkWidget *label34;
  GtkWidget *label33;
  GtkWidget *comboboxentry5;
  GtkWidget *label35;
  GtkWidget *comboboxentry6;
  GtkWidget *calendar1;
  GtkWidget *label38;
  GtkWidget *comboboxentry7;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *button16;
  GtkWidget *alignment13;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label40;
  GtkWidget *button15;
  GtkWidget *alignment12;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label39;
  GtkWidget *button19;
  GtkWidget *alignment18;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label59;

  entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (entraineur), _("entraineur"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (entraineur), fixed9);

  label34 = gtk_label_new (_("Nom de l'equipement:"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed9), label34, 16, 88);
  gtk_widget_set_size_request (label34, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label34), 0.45, 0.5);

  label33 = gtk_label_new (_("Reserver un equipement:"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed9), label33, 104, 24);
  gtk_widget_set_size_request (label33, 176, 48);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry5, 184, 88);
  gtk_widget_set_size_request (comboboxentry5, 189, 29);

  label35 = gtk_label_new (_("non de l'entraineur:"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed9), label35, 16, 128);
  gtk_widget_set_size_request (label35, 136, 40);

  comboboxentry6 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry6);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry6, 184, 136);
  gtk_widget_set_size_request (comboboxentry6, 189, 29);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed9), calendar1, 176, 184);
  gtk_widget_set_size_request (calendar1, 260, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label38 = gtk_label_new (_("Nom Du Cours:"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed9), label38, 24, 400);
  gtk_widget_set_size_request (label38, 136, 40);

  comboboxentry7 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry7);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry7, 168, 408);
  gtk_widget_set_size_request (comboboxentry7, 189, 29);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton4, 184, 464);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  label36 = gtk_label_new (_("Heure Du Cours:"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed9), label36, 40, 448);
  gtk_widget_set_size_request (label36, 136, 40);

  label37 = gtk_label_new (_("Duree Du Cours:"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed9), label37, 32, 512);
  gtk_widget_set_size_request (label37, 136, 40);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton5, 184, 520);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed9), button16, 360, 632);
  gtk_widget_set_size_request (button16, 136, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button16), alignment13);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox10), label40, FALSE, FALSE, 0);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed9), button15, 24, 632);
  gtk_widget_set_size_request (button15, 128, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button15), alignment12);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox9), label39, FALSE, FALSE, 0);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed9), button19, 184, 632);
  gtk_widget_set_size_request (button19, 146, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button19), alignment18);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Reset"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox15), label59, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (entraineur, entraineur, "entraineur");
  GLADE_HOOKUP_OBJECT (entraineur, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (entraineur, label34, "label34");
  GLADE_HOOKUP_OBJECT (entraineur, label33, "label33");
  GLADE_HOOKUP_OBJECT (entraineur, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (entraineur, label35, "label35");
  GLADE_HOOKUP_OBJECT (entraineur, comboboxentry6, "comboboxentry6");
  GLADE_HOOKUP_OBJECT (entraineur, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (entraineur, label38, "label38");
  GLADE_HOOKUP_OBJECT (entraineur, comboboxentry7, "comboboxentry7");
  GLADE_HOOKUP_OBJECT (entraineur, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (entraineur, label36, "label36");
  GLADE_HOOKUP_OBJECT (entraineur, label37, "label37");
  GLADE_HOOKUP_OBJECT (entraineur, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (entraineur, button16, "button16");
  GLADE_HOOKUP_OBJECT (entraineur, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (entraineur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (entraineur, image10, "image10");
  GLADE_HOOKUP_OBJECT (entraineur, label40, "label40");
  GLADE_HOOKUP_OBJECT (entraineur, button15, "button15");
  GLADE_HOOKUP_OBJECT (entraineur, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (entraineur, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (entraineur, image9, "image9");
  GLADE_HOOKUP_OBJECT (entraineur, label39, "label39");
  GLADE_HOOKUP_OBJECT (entraineur, button19, "button19");
  GLADE_HOOKUP_OBJECT (entraineur, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (entraineur, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (entraineur, image19, "image19");
  GLADE_HOOKUP_OBJECT (entraineur, label59, "label59");

  return entraineur;
}

